sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ybassem/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ybassem/docker-react npm run test